[build]
  base = "vite-project"  # Folder names are case-sensitive on Netlify (should match actual folder name exactly)
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

